### ISSUE TITLE
Kedro Experiment Tracking Product Marketing Strategy

### ISSUE THREAD

**Issue by NeroOkwa** [kedro-org/kedro-viz#1240]
## Context

This captures all the product marketing activities to promote  and encourage awareness and adoption of Kedro Experiment Tracking. 

This includes updating the documentation, preparing a blog post, presentation, and webinar, and distributing the content beyond the existing [Kedro slack](https://join.slack.com/t/kedro-org/shared_invite/zt-1eicp0iw6-nkBvDlfAYb1AUJV7DgBIvw) organisation. 

### Goal
The goal is to  increase adoption of kedro experiment tracking adoption especially Kedro-Viz/Kedro users by 30%.

### Target audience
This is targeted to (DS, DE, and low tech)users with a 2 prong approach:

1. Marketing to kedro users to use kedro-viz
2. Marketing to non-kedro users to use kedro/kedro-viz

## Content
This would include:
- What is experiment tracking?
- Why Kedro implemented experiment tracking?
- Why would you choose to use experiment tracking in Kedro vs other tools?
- What features are in experiment tracking for Kedro?
- How did we get to this version of experiment tracking? (user testing process)
- What's the future of this feature?

This content would then be repurposed for different forms and mediums.

## Plan/Checklist
Admin:
- [ ] Create Github issues to track product marketing strategy and sub-activities - blog post e.t.c.
- [ ] Metrics - Determine success metrics for product marketing, and feature adoption

Key Activities:
- [ ] Update Kedro-Viz docs [#2144](https://github.com/kedro-org/kedro/issues/2144#issuecomment-1370997055) and spaceflight tutorial
- [ ] Write and publish blog article - [#1227 ](https://github.com/kedro-org/kedro-viz/issues/1227)
- [ ] Webinar - Present and record a webinar walkthrough on kedro experiment tracking (especially for existing users of experiment tracking and user interview/testing participants) 
- [ ] Do a google search on experiment tracking, to benchmark other related content for messaging and positioning 
- [ ] Presentation - prepare a presentation for internal & external audiences on kedro experiment tracking
- [ ] Explore other channels beyond Slack, to reach  users

**Comment by stichbury** [comment]
This is nice! I would add to your list of Key Activities 

- [ ] Create a set of content that compares experiment tracking in Kedro to the 3 (or 5) most likely "competitors". This content could be video scripts (to film at a later stage) or just text to publish as potential blog posts or other content marketing.


I'd also tie back the list you have added to the "Content" section with the activities list. So make it clear which task answers which of the content requirements.
