### ISSUE TITLE
Create/update all the Kedro touch points with new assets in alignment with rebrand guidelines 

### ISSUE THREAD

**Issue by Mackay031** [kedro-org/kedro-viz#1326]
This is the home of all things related to the Kedro Rebrand where we:
- Identify and create new assets for Kedro touch points
- Update existing assets to align with new guidelines

This is the follow on from Kedro Brand Refresh kedro-org/kedro-viz#1255 in the roadmap.

## Todo

- [x] kedro-org/kedro-website#115
- [x] kedro-org/kedro-viz#1328
- [x] kedro-org/kedro-viz#1329
- [ ] kedro-org/kedro-viz#1330
- [x] kedro-org/kedro-viz#1331
- [x] kedro-org/kedro-viz#1332
- [x] kedro-org/kedro-viz#1333
- [x] kedro-org/kedro-viz#1334
- [x] kedro-org/kedro-viz#1335
- [x] kedro-org/kedro-viz#1336
- [x] kedro-org/kedro-viz#1340
- [x] kedro-org/kedro-viz#1337
- [x] kedro-org/kedro-viz#1338
- [x] kedro-org/kedro-viz#1339

**Comment by tynandebold** [comment]
We can mark this as completed now, even though https://github.com/kedro-org/kedro-viz/issues/1330 is unchecked. That will come later.
