### ISSUE TITLE
Rebrand: Update Kedro-Artwork repo with new brand assets & rename

### ISSUE THREAD

**Issue by Mackay031** [kedro-org/kedro-viz#1331]
https://github.com/kedro-org/kedro-artwork

Assets for this ticket can be found here - https://mckinsey.ent.box.com/folder/209763404109

## Tasks

- [x] Update all assets in this repo with new brand assets
- [x] Upload the brand guidelines
- [x] Rename the repo to 'Kedro Brand Identity'

**Comment by stephkaiser** [comment]
@yetudada to reach out to Ibrahim to check on updating//renaming the repo
