### ISSUE TITLE
Rebrand: Create Slack assets

### ISSUE THREAD

**Issue by Mackay031** [kedro-org/kedro-viz#1335]
## Tasks

Kedro-Org

- [x] Create and update icon used to represent Kedro-Org workspace
- [x] Create and update icon used to represent :kedro:
- [x] Create and update icon for :kedroid:
- [ ] Crate workspace colour theme (low priority): https://slack.com/intl/en-gb/help/articles/205166337-Change-your-Slack-theme

Internal Slack

- [x] Create and update icon used to represent :kedro:
- [x] Create and update icon for :kedroid:
