### ISSUE TITLE
Rebrand: Create PowerPoint presentation templates

### ISSUE THREAD

**Issue by Mackay031** [kedro-org/kedro-viz#1337]
## Tasks

- [ ] Replace main deck with rebranded version. Current deck is here: https://mckinsey.ent.box.com/file/547796370965?v=kedro-technical-presentation
- [ ] Create experiment tracking deck version
- [x] Create kedro powerpoint templates with new brand guidelines

**Comment by rashidakanchwala** [comment]
link here to rebranded deck - https://mckinsey.ent.box.com/file/1233263829737 

The images and logos are adapted to dark UI. So image text isn't seen on white UI. Also most images don't suit the light UI.

**Comment by astrojuanlu** [comment]
What's the best way to move this forward currently? For now I'm using the old deck.

**Comment by stichbury** [comment]
Probably send this to the VG team for a first pass because we are at capacity for design in the team right now?

**Comment by astrojuanlu** [comment]
We agreed to prepare a brief for the VG team.

**Comment by stephkaiser** [comment]
hey @astrojuanlu I think this ticket isn't done yet as it includes updating existing kedro decks with the new powerpoint template - unless you think that should be a separate ticket?

**Comment by astrojuanlu** [comment]
Oh sorry, I thought it was only for the templates - thanks for the heads up, reopening

**Comment by tynandebold** [comment]
@stephkaiser said this is good to go, so I'm closing this.

**Comment by stephkaiser** [comment]
Kedro PPT Template with Inter typeface here - https://mckinsey.ent.box.com/folder/222611706439
Updated Kedro Technical Presentation here - https://mckinsey.ent.box.com/file/1288051571467
