### ISSUE TITLE
Enhance Kedro-viz doc integration process

### ISSUE THREAD

**Issue by stichbury** [kedro-org/kedro-viz#1637]
## Description
The outcome of https://github.com/kedro-org/kedro/issues/2600 is that Viz now has its own docs in this repository.

That means that the engineers working on Viz now have responsibility for them, and as part of handover, there are a few tasks that you'll need to pick up and complete, with guidance from Framework.

## Tasks

- [ ] Update continuous integration to run a linter across the Viz docs
- [ ] Update GitHub actions to run the Vale "language linter" on changes to the Viz docs (@ankatiyar is well-placed to help with this as [she worked on the Framework docs](https://github.com/kedro-org/kedro/issues/2518))
- [ ] Revise the way the project initiates and runs a Sphinx build to more closely follow the Framework approach with a `build-docs.sh` that is initiated from a makefile. At present we run `make html` created by Sphinx.

cc @rashidakanchwala

**Comment by astrojuanlu** [comment]
Adding making use of https://github.com/kedro-org/kedro-sphinx-theme for consistency

Essentially doing the equivalent of https://github.com/kedro-org/kedro/pull/3675
