### ISSUE TITLE
The Run Command Component in kedro-viz (General)

### ISSUE THREAD

**Issue by Huongg** [kedro-org/kedro-viz#1945]
## Description
The run command component will display the real-time command needed to achieve the current view in viz. This ticket is part of the larger ticket #1784, "Make Kedro-Viz flowchart filterable."

## Context
This feature is important because it allows users to see the exact commands required to replicate the current visualization. This helps users understand how it can be run the kedro framework via CLI, enabling better debugging, learning, and sharing of workflows. 

## Tasks:

- [ ] Design the user interface for the run command component.
- [ ] Implement the logic to generate and update commands in real time based on the current visualization state.
- [ ] Ensure the command line shown in viz is integrates smoothly with the existing approach from framework.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by Huongg** [comment]
As discussed with @stephkaiser, I'm now going to do a spike work on how this works technically first while she's looking at the design for [1944](https://github.com/kedro-org/kedro-viz/issues/1944)

cc @rashidakanchwala @jitu5

**Comment by Huongg** [comment]
I've done a first around of spike work [here](https://github.com/kedro-org/kedro-viz/tree/spike-run-command), where I created a new selector to handle all the command lines and connect with the UI component

<img width="1510" alt="Screenshot 2024-07-04 at 12 32 38" src="https://github.com/kedro-org/kedro-viz/assets/32060364/2b5b0a93-d969-4918-b147-ec075c164857">


A gif to briefly show how the flow works at the moment:

![runcommand-ezgif com-video-to-gif-converter](https://github.com/kedro-org/kedro-viz/assets/32060364/9e717725-a8d7-434c-9ca4-7b841d5ebddf)

**Comment by rashidakanchwala** [comment]
Is this done? @Huongg

**Comment by Huongg** [comment]
hey @rashidakanchwala  not 100% done, it's only done for the slicing pipeline part, but not for other features

**Comment by Huongg** [comment]
@stephkaiser has led the design work for the run-command, which you can view [here](https://www.figma.com/design/3kSpvIO1veLKfy9qHxuXwF/Kedro-WIP?node-id=1469-56945&node-type=canvas&m=dev)

<img width="576" alt="Screenshot 2024-11-13 at 10 12 37" src="https://github.com/user-attachments/assets/d7004abc-232f-4d79-ab63-b28fe47fbf48">

The next step will be to decide where in the UI the run command should appear—such as when switching pipelines or selecting a node/element? 

cc @astrojuanlu and @stephkaiser for any further discussion on this

**Comment by ElenaKhaustova** [comment]
@ravi-kumar-pilla, @Huongg TODO: double-check if this ticket is still relevant

**Comment by Huongg** [comment]
Hi I suggest to close this issue as it's not longer needed
