### ISSUE TITLE
Refactor NodeList Component

### ISSUE THREAD

**Issue by rashidakanchwala** [kedro-org/kedro-viz#2037]
## Description

Our Nodelist component is too confusing. We have a lot of nested components, and most of the time we pass props from parent to child but sometimes we also connect the child to redux state and get props directly from the state. This ticket is to rethink this component properly and refactor it. 

- [x] https://github.com/kedro-org/kedro-viz/pull/2143
- [x] https://github.com/kedro-org/kedro-viz/issues/2153
- [x] https://github.com/kedro-org/kedro-viz/issues/2154
- [x]  https://github.com/kedro-org/kedro-viz/issues/2155

## Context
Why is this change important to you? How would you use it? How can it benefit other users?

## Possible Implementation
(Optional) Suggest an idea for implementing the addition or change.

## Possible Alternatives
(Optional) Describe any alternative solutions or features you've considered.

## Checklist

- [ ] Include labels so that we can categorise your feature request

**Comment by Huongg** [comment]
As per our team discussions, the refactoring will be executed in multiple phases:

Miro board for the plan: https://miro.com/app/board/uXjVLTeWe88=/

<img width="918" alt="Screenshot 2024-10-25 at 12 58 57" src="https://github.com/user-attachments/assets/bc4b02f9-73e5-4223-8c8d-b9c95ea58918">


- [ ] Phase 1: Refactor the node-list-row component. [PR-2143](https://github.com/kedro-org/kedro-viz/pull/2143)
- [ ] Phase 2: Separate and refactor the node-list-groups (also known as filter groups) from the node-list component. [Issue-2153](https://github.com/kedro-org/kedro-viz/issues/2153)
- [ ] Phase 3: Refactor the node-list-tree component [issue-2154](https://github.com/kedro-org/kedro-viz/issues/2154)
- [ ] Phase 4: Refactor the parent component and the state management of the node-list. [issue-2155](https://github.com/kedro-org/kedro-viz/issues/2155)
