### ISSUE TITLE
Remove experiment tracking

### ISSUE THREAD

**Issue by astrojuanlu** [kedro-org/kedro-viz#2202]
After a discussion in which we considered keeping Experiment Tracking as-is, doing more development work (for example #2152), removal https://github.com/kedro-org/kedro-viz/discussions/1831, and making it optional #2079 , with a heavy heart we ended up picking complete removal. There isn't nearly enough user traction and we aren't confident we can make the feature good enough to make people switch over the alternatives.

I think we can proceed without a deprecation warning. This would be a breaking release.

As follow-ups, we'll also hold a retrospective to learn from this experience.

**Comment by tynandebold** [comment]
Can I work on this, at least removing the frontend part?

cc @rashidakanchwala

**Comment by astrojuanlu** [comment]
I have no problem with that @tynandebold!

**Comment by astrojuanlu** [comment]
@rashidakanchwala will make the call

**Comment by Huongg** [comment]
After discussing with @tynandebold , here are the three subtasks that need to be completed under this ticket:

- [ ] 1. Remove Front-End Components: This includes the UI, e2e tests, and Apollo queries. Estimation: 1–3 points
- [ ] 2. Remove Back-End Components: This includes GraphQL Strawberry, the SQL session store, and associated tests. Estimation: 3–5 points
- [ ] 3. Update Documentation and References: Remove any references to ET, including Medium articles, YouTube content, and draft a release announcement to address the breaking changes. Estimation: 1–3 points

**Comment by ankatiyar** [comment]
While reviewing https://github.com/kedro-org/kedro-starters/pull/262, I was wondering if we need the `spaceflights-pandas-viz` and the `spaceflights-pyspark-viz` starters and the "kedro-viz" tool in the project creation flow at all?

The difference between `spaceflights-pandas` and `spaceflights-pyspark-viz` is a "reporting" pipeline AND the experiment tracking stuff in the `settings.py`. `Kedro-Viz` is in the requirements of all spaceflights starters by default. The "reporting" pipeline is not a part of the project unless you select `--tools=viz --example=y`. With experiment tracking gone, we could probably get rid of the extra tool and starters? 🤔

**Comment by ravi-kumar-pilla** [comment]
> The difference between `spaceflights-pandas` and `spaceflights-pyspark-viz` is a "reporting" pipeline AND the experiment tracking stuff in the `settings.py`. `Kedro-Viz` is in the requirements of all spaceflights starters by default. The "reporting" pipeline is not a part of the project unless you select `--tools=viz --example=y`. With experiment tracking gone, we could probably get rid of the extra tool and starters? 🤔

That is a good call. I think without experiment tracking, we can actually remove both the starters. But it would affect Kedro-Viz visibility too

**Comment by ravi-kumar-pilla** [comment]
Hi Team,

Since we are removing tracking datasets, we also need to work on -
1. https://github.com/kedro-org/kedro/issues/4258 (The jsonschema is already present in kedro-datasets, it needs to be removed from kedro - `kedro/static/jsonschema`)
2. Since the json schema is part of kedro-datasets, the schema files need to be renamed reflecting kedro-dataset releases instead of kedro-catalog (i.e., kedro-datasets-x.x.json instead of kedro-catalog-x.xx.json). I will create a new ticket if the team feels this is needed (as Nok was mentioning kedro-vscode will not rely on these json files in future, so there is also a question on should we remove them completely ? )

Both the above issues are not blockers for the parent ticket but it would be great to get clarity on these json schema files. 

Thank you

**Comment by astrojuanlu** [comment]
We are working on a communications plan and a retrospective.

**Comment by rashidakanchwala** [comment]
Migration from Kedro-Viz Native Experiment Tracking to Kedro-Mlflow 

| **Kedro-Viz Dataset Type**           | **MLflow Dataset Type**        | **Configuration Details**                       |
|--------------------------------------|---------------------------------|------------------------------------------------|
| `tracking.MetricsDataset`           | `MlflowMetricDataset`          | No additional configuration needed.            |
| `tracking.JSONDataset`              | `MlflowArtifactDataset`        | Wrap within `MlflowArtifactDataset` and configure as `json.JSONDataset`. |
| `plotly.plotlyDataset`              | `MlflowArtifactDataset`        | Wrap within `MlflowArtifactDataset`.           |
| `plotly.JSONDataset`                | `MlflowArtifactDataset`        | Wrap within `MlflowArtifactDataset`.           |
| `matplotlib.MatplotlibWriter`       | `MlflowArtifactDataset`        | Wrap within `MlflowArtifactDataset`.           |

**Comment by astrojuanlu** [comment]
Release deprecating Experiment Tracking went out #2254 

The actual removal can now proceed

**Comment by astrojuanlu** [comment]
Added https://github.com/kedro-org/kedro-starters/issues/263 as a sub-issue of this one

**Comment by astrojuanlu** [comment]
It's actually not a blocker to remove ET from Viz. We can now proceed.
